export type IpcChannels =
  | 'WINDOW_MINIMIZE'
  | 'WINDOW_MAXIMIZE'
  | 'APP_EXIT'
  | 'DISCORD_READY'
  | 'DISCORD_GET_GUILDS'
  | 'DISCORD_LOAD_CHANNEL'
  | 'DISCORD_LOAD_GUILD'
  | 'DISCORD_GET_LAST_VISITED_GUILD_CHANNEL'
  | 'DISCORD_SET_LAST_VISITED_GUILD_CHANNEL';
